# ベースイメージを指定
FROM gcr.io/etcd-development/etcd:v3.4.13

# ポートの公開
EXPOSE 2379

# データディレクトリの作成
RUN mkdir -p /etcd-data

# ボリュームの指定
VOLUME /etcd-data

# etcdの実行コマンドを指定
CMD ["/usr/local/bin/etcd", \
     "--name=etcd-1", \
     "--data-dir=/etcd-data", \
     "--advertise-client-urls", "http://0.0.0.0:2379", \
     "--listen-client-urls", "http://0.0.0.0:2379"]